### ISSUE TITLE
Tested on EdgeRouter 6P - works flawlessly

### ISSUE THREAD

**Issue by moecre** [x70b1/telegraf-edgeos#1]
Hi @x70b1,

first of all thank you for this great tool!

I was using Telegraf on various other network components already but to be able to gather stats directly on the router and sending them to my existing InfluxDB/Grafana setup is bliss!! Very well done for this mips package of telegraf.

<img width="756" alt="image" src="https://user-images.githubusercontent.com/1425946/167432504-029952a9-2c76-41f0-b7ff-7edda6d03882.png">

So to extend your compatibility list for the ER-6P:

Internal plugins: Check
firmware: Check
interfaces: Check
power: Check
temperatures: Cross (this is not working)

Here's a screen of my Dashboard:

<img width="1856" alt="Screenshot 2022-05-09 at 3 26 02 pm" src="https://user-images.githubusercontent.com/1425946/167433110-4728a658-5b09-43ee-9558-23e42aade7d0.png">

Again thank you and let me know if I can help in the future (I was thinking of tapping into the DPI data of the router somehow).

**Comment by x70b1** [comment]
I am happy that this project is also helpful for you :sunglasses: 

Thanks for the feedback, I will update the table for ER-6P.

If you have ideas about improvements, just share them. DPI is something that I dont use. The chances that I will work on this is very low. So if you want to start to work on it or other topics, that would be cool.

**Comment by x70b1** [comment]
I added ER-6P in https://github.com/x70b1/telegraf-edgeos/commit/c413b9452fc174d7ae586cd706a69e3702aecc82.

Thanks!
