### ISSUE TITLE
Telegraf Plugin - Ping?

### ISSUE THREAD

**Issue by danfoxley** [x70b1/telegraf-edgeos#11]
Any thought on enabling Telegraf Ping plugin?  I know there are Linux permission particulars, but would be nice to have ping stats from the erlite-4 point of view. Would I be able to add another exec in the config, I see there is one in use already.

Thanks for the this!

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/ping/README.md

**Comment by x70b1** [comment]
The `ping` input should be already there. You can run `$ telegraf --input-list` to check this.
