### ISSUE TITLE
Question about Grafana

### ISSUE THREAD

**Issue by TakeusV1** [x70b1/telegraf-edgeos#14]
Hi, I've successfully installed and configured telegraf on my "ER-X", and I'm now able to retrieve data from my influxdb database. But i'm not a grafana power user, I don't know how to link the influx database to the dashboard template, I'm not proposed to choose my influxdb database when I import the dashboard but usually with other dashboard, I'm invited to choose my database.

![1](https://github.com/x70b1/telegraf-edgeos/assets/68923554/f3397f3a-e7f6-4bfd-9bec-c54112336d15)

But if I import another dashboard (like a proxmox dashboard) :
![2](https://github.com/x70b1/telegraf-edgeos/assets/68923554/e236332f-07b2-49fc-a401-fcca7cfdfaf4)

I know I have to modify the json model, but I would have liked to have more precision on the elements to be modified...

```
"datasource": {
        "type": "influxdb",
        "uid": "P12F67F8539C46701"
},
```
I have the impression that this part needs to be modified, but I can't find a value close to this one (UID).

**Comment by x70b1** [comment]
I guess you have to change the Datasources manually for all graphs. 
Its a long time ago that I worked on that Grafana Dashboard.
