### ISSUE TITLE
jq is not installed

### ISSUE THREAD

**Issue by bfenty** [x70b1/telegraf-edgeos#7]
Getting an error that jq is not installed. When I try to install it, it says "trying to overwrite '/usr/bin/jq', which is also in package ubnt-util 0.1.29+t5274261-dev-v1.10.11-095c25c". I'm assuming this is installed as part of the base image and dpkg isn't recognizing that?

I'm on an Edgerouter-X running v1.10.11-095c25c.

**Comment by x70b1** [comment]
The question is if it is there, why isnt it recognized? 
Is `/usr/bin/` part of your PATH? I think so. Everthing else would be crazy. 

The only place where we use jq is at the firmware status collection. Is it working without firmware stats?

**Comment by x70b1** [comment]
Could you find out whats wrong here?
