### ISSUE TITLE
enable more output plugins

### ISSUE THREAD

**Issue by timvy** [x70b1/telegraf-edgeos#9]
I would like to use Telegraf to send data from my edgerouter to Splunk. For that i need the http output plugin. Is that possible? How could i create that package?

**Comment by x70b1** [comment]
Thats possible if you build your own package. You can take a look at the [build file](https://github.com/x70b1/telegraf-edgeos/blob/master/.github/workflows/release.yml).

At the moment we have 3 outputs configured:

```
  TELEGRAF_OUTPUTS: outputs.influxdb,outputs.influxdb_v2,outputs.prometheus_client
```

But my plan was also to enable other output plugins. 
I could look at this later.

**Comment by timvy** [comment]
Okay, thanks! I'll play around with the build, see if i can make it work.

**Comment by x70b1** [comment]
@timvy I introduced some bigger changes in the build pipeline (https://github.com/x70b1/telegraf-edgeos/commit/9fd30b1046294857233b8de12a77005738d68346). 
We now have flavors. I also set up one for http and splunk. Can you try it out with the latest [release](https://github.com/x70b1/telegraf-edgeos/releases/tag/v1.26.0-1)?

**Comment by timvy** [comment]
Great! I installed this on my edgerouter, and it is sending metrics to Splunk. It works! 
When i use the config from https://www.splunk.com/en_us/blog/it/splunk-metrics-via-telegraf.html for data normalization, it suggests to use the rename processor plugin. Is that something that can be added as well?

**Comment by timvy** [comment]
@x70b1 nevermind my previous request. I am now using the app Operating System monitoring with Telegraf, found here:
https://splunkbase.splunk.com/app/4271
Renaming and processing the fields isn't necessary anymore, as this apps works with all the default Telegraf fields.
It works great. I do limit the data to only strictly necessary fields, otherwise Telegraf uses a lot of cpu on the router.

**Comment by x70b1** [comment]
@timvy I would build this into our Telegraf.

**Comment by x70b1** [comment]
You can try the [latest build](https://github.com/x70b1/telegraf-edgeos/actions/runs/4478439251#artifacts).

**Comment by x70b1** [comment]
@timvy Is it working? Then we could close this topic.

**Comment by timvy** [comment]
It's working perfectly. Thanks very much for your work!

**Comment by x70b1** [comment]
🫡
